default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: mamma_map_development

test:
  <<: *default
  database: mamma_map_test

production:
  <<: *default
  database: mamma_map_production
  username: 
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>

